sonar.projectKey=" "
sonar.organization=" "
sonar.projectName=UltraInstinctVR
sonar.sources=CodeBase/Assets
sonar.language=cs
sonar.host.url=https://sonarcloud.io
sonar.login=<SONAR_TOKEN>
sonar.sources=CodeBase/Scripts
